################
### AUTOSTART ###
#################

exec-once = quickshell
exec-once = nm-applet
exec-once = blueman-applet
exec-once = copyq
exec-once = swww-daemon &
exec-once = swaync 
exec-once = waybar
# exec-once = mcontrolcenter
